### ISSUE TITLE
Feature Request: Remember Last Used IP

### ISSUE THREAD

**Issue by EnigmaSolved** [seliver/ElpisRemote#3]
Currently ER (ElpisRemote) doesn't remember the last used IP on subsequent app starts. It would be convenient if this were different.

I recommend that eventually there be an interface for remembering multiple servers (and defining one as Default). [Panmote](https://play.google.com/store/apps/details?id=com.jkieliszak.panmote&hl=en) does this well. It has a Server screen where you can define multiple Server IP's, and Scan for Servers (I think the Scan button is the wifi icon the below image; current versions use a magnifying glass, which is a better choice in my opinion).

![Panmote Server Screen](https://lh5.ggpht.com/gX14FhEAWiSUsEuCJN0mtWJ-DS2YnZ61LYGNZX24g5KLDWnteqDln_G3SNBNNTiTgA=h900)

When Panmote loads up you briefly see the Server screen while it scans and connects, and then once it connects it switches to the Player screen.  This is a decent UI flow.

**Comment by seliver** [comment]
Closing this as it is solved in 1.0.6.

**Comment by EnigmaSolved** [comment]
Sounds good!
